# Generated by Django 4.2.11 on 2024-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='url',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
