# Generated by Django 4.2.11 on 2024-05-25 15:27

from django.db import migrations, models
import oniria_project.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_profile_image_profileimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=oniria_project.users.models.upload_path),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
