# Generated by Django 4.2.11 on 2024-03-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('dream_date', models.DateField(verbose_name='Fecha del Sueño')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('privacy', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('friends', 'Solo amigos')], default='private', max_length=10, verbose_name='Privacidad')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
