# Generated by Django 4.2.11 on 2024-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0005_post_people_involved_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['is_default'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='peopleinvolved',
            options={'ordering': ['name'], 'verbose_name_plural': 'People Involved'},
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
