# Generated by Django 4.2.11 on 2024-04-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0006_alter_category_options_alter_peopleinvolved_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oniria_app.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='people_involved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oniria_app.peopleinvolved'),
        ),
    ]
