# Generated by Django 4.2.11 on 2024-04-06 10:46

from django.db import migrations, models
import oniria_project.oniria_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0007_alter_post_category_alter_post_people_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dream_date',
            field=models.DateField(validators=[oniria_project.oniria_app.validators.validate_not_future_date], verbose_name='Fecha del Sueño'),
        ),
    ]
