# Generated by Django 4.2.11 on 2024-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0008_alter_post_dream_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='people_involved',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='oniria_app.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='people_involved',
            field=models.ManyToManyField(blank=True, to='oniria_app.peopleinvolved'),
        ),
    ]
