# Generated by Django 4.2.11 on 2024-05-06 17:10

from django.db import migrations, models
import oniria_project.oniria_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0012_alter_category_options_peopleinvolved_linked_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinvolved',
            name='linked_username',
            field=models.CharField(blank=True, null=True, validators=[oniria_project.oniria_app.validators.validate_username]),
        ),
    ]
