# Generated by Django 4.2.11 on 2024-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0013_peopleinvolved_linked_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleinvolved',
            name='linked_username',
        ),
    ]
