# Generated by Django 4.2.11 on 2024-05-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0014_remove_peopleinvolved_linked_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
    ]
