# Generated by Django 4.2.11 on 2024-05-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniria_app', '0015_remove_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación Pública'),
        ),
    ]
